USE [master]
GO

/****** Object:  Database [AUTOS]    Script Date: 21/04/2023 09:09:56 a. m. ******/
CREATE DATABASE [AUTOS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AUTOS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\AUTOS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AUTOS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\AUTOS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AUTOS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AUTOS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AUTOS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AUTOS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AUTOS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AUTOS] SET ARITHABORT OFF 
GO

ALTER DATABASE [AUTOS] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [AUTOS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AUTOS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AUTOS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AUTOS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AUTOS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AUTOS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AUTOS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AUTOS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AUTOS] SET  ENABLE_BROKER 
GO

ALTER DATABASE [AUTOS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AUTOS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AUTOS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AUTOS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AUTOS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AUTOS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AUTOS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AUTOS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AUTOS] SET  MULTI_USER 
GO

ALTER DATABASE [AUTOS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AUTOS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AUTOS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AUTOS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AUTOS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AUTOS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [AUTOS] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AUTOS] SET  READ_WRITE 
GO


